### ISSUE TITLE
bibtex-ruby should not convert strings entries to integer

### ISSUE THREAD

**Issue by DamienRobert** [inukshuk/bibtex-ruby#100]
For instance

    BibTeX::Entry.new({eprint: " 1001.1234"}).to_s
    # => "@{unknown-a,\n  eprint = {1001}\n}\n"

The eprint field is used by biblatex to put hyperlinks (here this is an arxiv reference). If the strings get mangled, the reference is not valid anymore. It looks as if bibtex-ruby is trying to convert the string to an integer, even though I gave him a string and not an integer. I guess this could make sense for some fields (eg 'page') but not for all fields.
This behaviour was not happening in older versions, I can bisect it to check when the regression happened if you need.
Thanks!

**Comment by inukshuk** [comment]
Thanks for reporting!

Yes, indeed, this was introduced recently, because we wanted to sort numeric values as numbers, but obviously the conversion should not happen when calling `#to_s`

**Comment by inukshuk** [comment]
Fixed in 4.0.10

**Comment by DamienRobert** [comment]
From Sylvester Keil, Fri 23 Jan 2015 at 09:52:58 (-0800) :
> Fixed in 4.0.10

I confirm that it works, thanks! I am impressed by your reactivity!
