### ISSUE TITLE
Query for BibTeX field:type impossible

### ISSUE THREAD

**Issue by iiegn** [inukshuk/bibtex-ruby#104]
`b.q('@misc[type=something]')`, i.e. a query for the BibTeX *field* - not the entry type - is not possible. instead, it seems it has the somewhat unexpected behaviour of actually querying the entry type: `b.q('@misc[type=article]')`.

**Comment by inukshuk** [comment]
the bibtex type used to be stored in a field called type; we changed that a while ago in order to support the regular `type` field so this behaviour is probably a leftover. thanks for reporting!
