### ISSUE TITLE
Missing fields when going from biblatex to cite_proc

### ISSUE THREAD

**Issue by a-fent** [inukshuk/bibtex-ruby#106]
Hi, I'm reading from a Biblatex file (with `:filter => :latex`) but I'm missing a few fields when I eventually get to CSL.

Biblatex has *journaltitle* rather than Bibtex's *journal*, so the container-title field in to_citeproc is left empty, and journal titles are missing.

The report number field for type "report" is missing - I'm not quite sure what is happening here.

**Comment by inukshuk** [comment]
This is happening [here](https://github.com/inukshuk/bibtex-ruby/blob/master/lib/bibtex/entry/citeproc_converter.rb); the first problem should be easy to fix by simply adding the `journaltitle` to [CSL_FILTER](https://github.com/inukshuk/bibtex-ruby/blob/master/lib/bibtex/entry/citeproc_converter.rb#L2);

For the second one adding support for type 'report' [on line 95](https://github.com/inukshuk/bibtex-ruby/blob/master/lib/bibtex/entry/citeproc_converter.rb#L95) should do the trick.

I'll add this when I have the time, but a PR is much appreciated if you want to expedite the process.

**Comment by a-fent** [comment]
Thanks for the quick reply. I'll try and do a pull request.

On the first I wanted to check though if that should be fixed in 
to_citeproc (as in the proposed addition to CSL_FILTER) or in the 
Biblatex filter to Bibtex.read() - i.e. if the latter should mean 
"produce a bibtex standard representation of this, filtering as if it 
comes from Biblatex" it should be there no?

**Comment by inukshuk** [comment]
The `latex` filter's purpose is to convert LaTeX markup to unicode; it doesn't have to anything with BibLaTeX. Furthermore, we definitely want to support round-trip saving of BibLaTeX bibliographies, so we don't really want to change the bibliography itself; it should definitely go into the citeproc converter.
