### ISSUE TITLE
One <bibtex:author/> tag in extended BibTeXML

### ISSUE THREAD

**Issue by jocelynpender** [inukshuk/bibtex-ruby#112]
I'm using the bibtex-ruby package to convert my anystyle parser results to xml format, while preserving information about first and last names of authors and editors in my results. 

    x = Anystyle.parse(refs.text, format = :bibtex)
    xmlref = x[0].to_xml(:extended => true)

I've noticed that after conversion to xml, the output gives a `<bibtex:author/>` tag after all persons have been described. This also happens with editors (i.e., one `<bibtex:editor/>` tag). In your examples in the bibtex-ruby README, I also see only one `<bibtex:author/>` tag after person tags. 

I'm using this xml output with the Nokogiri gem. Nokogiri modifies the xml to give `<author></author>` on one line, after persons. Obviously this is a problem for being able to properly use the xml data down the line (because it does not identify the persons as the authors etc.). Is there some reason why there is only one `<bibtex:author/>` tag? Am I missing something? 

Thanks!

**Comment by inukshuk** [comment]
Thanks! Should be fixed in 4.1.1

**Comment by jocelynpender** [comment]
Just tried 4.1.1 and all tags are behaving properly. Thank you for addressing this so quickly, immense gratitude is due!
