### ISSUE TITLE
Program crash when parsing large BibTex strings

### ISSUE THREAD

**Issue by jheer** [inukshuk/bibtex-ruby#113]
I'm using jekyll-scholar with a large bibtex file and ran into an error that I tracked down into bibtex-ruby.

The offending line is [lib/bibtex/utilities.rb#L33](https://github.com/inukshuk/bibtex-ruby/blob/master/lib/bibtex/utilities.rb#L33). If the `string` input is so long as to be an invalid file name, the `File.exists?` call raises an error. A length check to ensure the string is not too long seems to suffice to fix the issue. That said, having the method change its behavior based on the string content (rather than an option) seems rather dangerous in general.

**Comment by inukshuk** [comment]
Thanks! I added an additional check; the method is for convenience since you ought to use open/parse directly depending on your input. Having said that, I changed the jekyll-scholar code in question to do just that.

**Comment by jheer** [comment]
Thanks!
