### ISSUE TITLE
Query Parsing is Space Sensitive

### ISSUE THREAD

**Issue by edgemaster** [inukshuk/bibtex-ruby#114]
I've just spent a while discovering that the query syntax is space sensitive around the square brackets, for example, the following queries produce no results (nor any parse warning).
* `@*[ author ~= Name ]`
* `@*[ author ~= Name]`
* `@*[author ~= Name ]`

If this is the intended behaviour (for example, to capture spaces at the end of the queried string), can it be documented please?

**Comment by inukshuk** [comment]
Good catch, thanks! This is fixed in bibtex-ruby 4.2.0 -- you should be able use that version without having to update jekyll-scholar.
