### ISSUE TITLE
Q: Decoding LaTeX formatting into unicode

### ISSUE THREAD

**Issue by retrography** [inukshuk/bibtex-ruby#117]
Is there any way to convert instructions like `Siobh\'{a}n` to unicode with this gem?

**Comment by inukshuk** [comment]
Yes. We actually moved this functionality into a separate gem `latex-decode` but it ships with `bibtex-ruby` by default. See [here](https://github.com/inukshuk/bibtex-ruby#filters)

**Comment by retrography** [comment]
Thanks!
