### ISSUE TITLE
Empty editor field leads to parse failure

### ISSUE THREAD

**Issue by dginev** [inukshuk/bibtex-ruby#123]
I found that the citation entry:
```bibtex
@Incollection{test,
  author = {author},
  title = {title},
  editor = {},
}
```

Lead the `BibTeX.open` call to throw the error:
```
 Failed to parse BibTeX Name on value "$" ($end) ["(^start)"]
```

Of course this is a minimal example with a fake citation, the real citation experiencing the issue had some 9 bibtex fields. But even for that removing the `editor = {},` fixed the problem.

Maybe this is an easy patch?

**Comment by inukshuk** [comment]
Does this actually fail for you, or it the problem just the error message? (I think an empty string is not accepted by the name parser, but that error should be rescued and the value assumed to be `nil`).

**Comment by inukshuk** [comment]
I changed the log level to debug in 4.4.4 to avoid confusion.

**Comment by dginev** [comment]
Perfect, thanks! This fix is quite helpful. 

The severity was indeed the problem, as I would be quite happy to get a usable parsed object with the warning messages - the current behavior was to raise a hard failure and halt.
