### ISSUE TITLE
Quote on identifier broke parser

### ISSUE THREAD

**Issue by clbustos** [inukshuk/bibtex-ruby#125]
WHen you export a Scopus query, its bibtex add single quotes on articles. That generates a  warning like
    WARN -- : Lexer: unexpected token `'' at 14; brace level 1; mode :entry
and stores a  BibTex::Error as data. The rest of the BibTex is well-formed, so is a little harsh to just mark as an error, when the standard is not clear about it.

**Comment by inukshuk** [comment]
Fixed in 4.4.5. Thanks for reporting!

**Comment by clbustos** [comment]
Amazing!!!! Thank you very much.
