### ISSUE TITLE
Add new software which uses bibtex-ruby

### ISSUE THREAD

**Issue by clbustos** [inukshuk/bibtex-ruby#127]
Buhos is a systematic literature review software that uses intensively bibtex-ruby for import and export. Can you add it?

BTW, how can I cite this library? I want to include a reference on a paper, and I can't find a canonical one.

**Comment by inukshuk** [comment]
You can edit the [wiki page](https://github.com/inukshuk/bibtex-ruby/wiki/Projects-Using-BibTeX-Ruby) if you'd like to add a link to Buhos.
