### ISSUE TITLE
Unable to parse bibtex if `+` is in the key

### ISSUE THREAD

**Issue by xu-cheng** [inukshuk/bibtex-ruby#128]
Below is an example of legal bibtex file. However, it cannot be properly parsed by bibtex-ruby due to the `+` character in the key `author+an`.

```bibtex
@article{foo
  title={Some Title},
  author={SureName1, GivenName 1 and SureName2, GivenName 2},
  author+an={1=highlight}
}
```

Trying to load it, it will report following message. Consequently, the entry will be missing in Jekyll-scholar.
```
W, [2018-03-01 20:16:51#3787]  WARN -- : Lexer: unexpected token `+' at 178; brace level 1; mode :bibtex.
```

For more information, `author+an` is an annotation supported by biblatex. It is mainly used to highlight specific author. Ref: https://www.linkedin.com/pulse/using-biblatex-conveniently-highlight-your-author-mark-coletti-phd

Further, it would be nice that `bibtex-ruby` and `jekyll-scholar` can support author highlight in such method. I understand such function can be achieved using regex replace. However, it is less reliable if there are authors with the same name especially when only using initials instead of full given name.

**Comment by inukshuk** [comment]
I was not aware of such annotations, but let's accept them by default if they are commonly used!

Note that you can already adjust the lexer patterns, e.g. the pattern used for field names is at: `BibTeX::Lexer.patterns[:name]`. (But I'll push a new version of the Gem shortly which accepts + by default.)

As for using the annotation in jekyll-scholar, that's a cool idea. PR welcome if you want to give it a try! But like you say, to do this properly we'd need to hook into the CSL renderer (to make you only highlight the author's name in the author field) which is not currently possible.
