### ISSUE TITLE
Does bibtex-ruby read all fields (PMID in specific)

### ISSUE THREAD

**Issue by shahryareiv** [inukshuk/bibtex-ruby#130]
I am trying to include PMID in my citations and there is a chain of gems and the CSL file that work together. But I could not figure out why PMID does not show in the final result. 

I checked and can see that PMID is supported in the that specific CSL (journal-of-medical-internet-research), the CSL is installed,  the gem that converts things is probably blind about what type of fields should be converted (https://github.com/asciidoctor/asciidoctor-bibtex), that is probably the same for Citeproc-Ruby. So the only member of the chain left is bibtex-ruby. 

Does bibtex-ruby read PMID from bibtex and provide it as CSL?

**Comment by shahryareiv** [comment]
I guess this is where PMID (and probably PMCID) are missing:
https://github.com/inukshuk/bibtex-ruby/blob/master/lib/bibtex/entry/citeproc_converter.rb

**Comment by inukshuk** [comment]
The list above is only for fields which need to be converted; if you have a PMID field in your BibTeX and you export it to CSL-JSON it should be passed through unchanged.

**Comment by inukshuk** [comment]
By final output you mean a reference formatted using the CSL style? The CSL field is called `PMID` (not `pmid`) so maybe it's just the different capitalization; in this case your original observation would be spot on and we could add a conversion from pmid to PMID when exporting to CSL JSON.

**Comment by shahryareiv** [comment]
Yes, exactly. I meant the reference formed by CSL style. For example the record 
```
@article{phichitchaisopa_factors_2013,
  timestamp = {2017-10-13T13:06:56Z},
  title = {Factors Affecting the Adoption of Healthcare Information Technology},
  volume = {12},
  issn = {1611-2156},
  doi = {10.17877/DE290R-5602},
  abstract = {},
  urldate = {2017-10-02},
  journal = {EXCLI Journal},
  author = {Phichitchaisopa, Nisakorn and Naenna, Thanakorn},
  month = may,
  year = {2013},
  pages = {413--436},
  pmid = {26417235},
  pmcid = {PMC4566918}
}
```
becomes:
```
Phichitchaisopa N, Naenna T. Factors Affecting the Adoption of Healthcare 
Information Technology. EXCLI Journal 2013 May;12:413–436.
 [doi: 10.17877/DE290R-5602]
```
missing both PMID and PMCID.

Note 1: I tried to manually change all `pmid` to `PMID` in the bibtex file but nothing changed in the final result.
Note 2: If bibtex-ruby wants to support Biblatex in future: Zotero uses different fields for PMID (have no idea why) when it exports to Bibaltex. Like this:
```
  eprinttype = {pmid},
  eprint = {16702590}
```

**Comment by inukshuk** [comment]
Well, we can add a conversion rule to upcase pmid and pmcid. Let's see if that helps!

Not sure what you mean by the second note: bibtex-ruby is just a bibtex-library. You can already use 'eprinttype' and 'eprint' like that if you want?

**Comment by shahryareiv** [comment]
Wow! It worked. Thanks for fixing that.

**Comment by shahryareiv** [comment]
Note 2 was just a hint if some day bibtex-ruby wants to support Biblatex. For some reason, Zotero exports PMID in two separate fields (eprinttype and eprint) in the Biblatex export mode. I have no idea why (or if it is  a bug?). But if it is the Biblatex way of handling PMID like fields then bibtex-ruby probably needs to combine those two fields.
