### ISSUE TITLE
Can this gem convert from CSL-JSON to BibTex?

### ISSUE THREAD

**Issue by coryschires** [inukshuk/bibtex-ruby#133]
Looking through the docs, it seems you must start with BibTex and from there can export various formats (including CSL-JSON). Is the opposite possible? I want to convert from CSL-JSON to BibTex.

Thanks again for creating this gem!

**Comment by inukshuk** [comment]
No, it isn't supported out of the box, but it should be trivial to do because you can pass a Ruby Hash to `Entry.new` (i.e., parse the JSON, flatten/convert it as needed and create the Entry) or something like that (there should be [plenty of examples](https://github.com/inukshuk/bibtex-ruby/blob/master/test/bibtex/test_entry.rb#L243)) how to create BibTeX entries in the tests).

**Comment by coryschires** [comment]
Thanks! Your suggestion makes sense, and I will probably go that route. 

That said, I would ideally like to use CSL-JSON as my "source of truth" (because I already have tooling for and familiarity with CSL-JSON) and then convert from CSL-JSON to a variety of other formats – most importantly BibTeX. In other words, I would rather not manage the mapping to convert between formats. I'm hoping a library can do this for me. 

But perhaps converting between formats is not the primary purpose / goal of this gem? So two questions:

#### 1. As far as you know, is there a different gem / library which is more appropriate for converting between formats?

#### 2. If not, would you be interested in something like:


    csl_json = "{\"id\":5116,\"type\":\"article-journal\",\"title\":\"Preferential placement for community structure formation\",\"container-title\":\"Internet Mathematics\",\"url\":\"https://doi.org/10.24166/im.06.2018\",\"DOI\":\"10.24166/im.06.2018\",\"volume\":\"1\",\"issue\":\"1\",\"issued\":{\"date-parts\":[[2018,11,8]]},\"author\":[{\"given\":\"Liudmila\",\"family\":\"Ostroumova Prokhorenkova\"},{\"given\":\"Egor\",\"family\":\"Samosvat\"},{\"given\":\"Aleksandr\",\"family\":\"Dorodnykh\"}]}"
    bib = BibTeX::Entry.new.from_citeproc(csl_json)
    
If so, I could probably make a pull request.

**Comment by inukshuk** [comment]
The purpose of this Gem, originally, was only to parse BibTeX; over time the API grew (manipulation, string replacements, queries, convert to other formats, etc.). I'd say 'parsing' other formats is not its main purpose, but I'm happy to merge a PR along those lines (maybe also add a `from_citeproc` to `Bibliography`, accepting an array of items?).

**Comment by inukshuk** [comment]
I'm not aware of any Gem which converts CSL-JSON to BibTeX.

**Comment by coryschires** [comment]
Hi! Thanks for following up.

Given that my use case is not a core responsibility of this gem, I decided to go another route. Because it may be helpful for others, I will describe my solution here. 

I've setup an [AWS Lambda](https://aws.amazon.com/lambda) which uses [Citation.js](https://citation.js.org/api/index.html) to convert between formats (e.g. convert CSJ-JSON to BibTex). 

The Lambda itself expects a payload of a JS object containing two keys: `csl_json` and `output_format`. It returns the citation metadata as a string in the specified metadata format.

The Lambda code itself is pretty simple:

```javascript
const Cite = require('citation-js');

exports.handler = async (event) => {
  let citation = new Cite(event.csl_json);
  let output = citation.format(event.output_format);

  const response = {
    statusCode: 200,
    body: output,
  };

  return response;
};
```

Maybe this will be useful to someone else?

Thanks again for your help!
