### ISSUE TITLE
Adding Rubocop

### ISSUE THREAD

**Issue by mapreal19** [inukshuk/bibtex-ruby#135]
Thoughts? I could help with this

**Comment by inukshuk** [comment]
Certainly, but this might be a lot of work : )

I wrote bibtex-ruby over ten years ago to learn Ruby and though it has evolved to being used in a few serious projects, it's still plainly obvious that it goes back to Ruby 1.8 days... so, adding Rubocop I think would probably call for dusting off the whole project a little bit and tidying up in lots of places. I guess what I'm trying to say is that I'm very much in low-key maintenance mode with this project -- if you're interested in helping out I'm more than happy to assist, but I'm not very involved with the project at the moment.

**Comment by mapreal19** [comment]
It's a lot of work if we want all the cops enabled at the first time ;)

I'm actively using this project in my own reference manager so I'll be glad to give a hand here

**Comment by inukshuk** [comment]
Alright, that's cool! I'll give you write access to the repo, but it's probably best to still work with PRs for anything except minor changes.

Would you like me to push major to rubygems now, or are you doing further police work?

**Comment by mapreal19** [comment]
@inukshuk haha 👮 I have some minor changes in progress but that can wait. I think now is best to push the major version and then work from there
