### ISSUE TITLE
warning: Capturing the given block using Proc.new is deprecated; use `&block` instead

### ISSUE THREAD

**Issue by attilagk** [inukshuk/bibtex-ruby#141]
Good morning!

I recently reinstalled ruby, jekyll and jekyll-scholar on Ubuntu 20.04 Desktop.  Now when I run `bundle exec jekyll serve` I get many warnings like the ones below.  [It looks like](https://blog.saeloun.com/2019/09/02/ruby-2-7-proc-without-block-warning.html) these warnings are due to my moving to ruby 2.7 (from 2.5).
```
/home/attila/gems/gems/bibtex-ruby-4.4.7/lib/bibtex/bibliography.rb:150: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead                                                                                                                            
/home/attila/gems/gems/bibtex-ruby-4.4.7/lib/bibtex/entry.rb:162: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead                                                                                                                                   
```

**Comment by inukshuk** [comment]
Yes, that's right. Please also update `bibtex-ruby` (probably `jekyll-scholar` too) and these warnings should go away. I think there might be some deprecations warnings left, especially in `latex-decode` which hasn't been touched in a long time -- but most of these deprecations should have been addressed some time ago. Certainly the examples above.
