### ISSUE TITLE
CiteProc.process returns nill (fails)

### ISSUE THREAD

**Issue by rseac** [inukshuk/bibtex-ruby#162]
Following the examples on the README do not work when using CiteProc.process.

```
> require 'bibtex'
> require 'citeproc'
> b = BibTeX.open('./test.bib')
> CiteProc.process b[:pickaxe].to_citeproc, :style=>:apa
=> nil
```

**Comment by inukshuk** [comment]
Those instructions look like they are for an older citeproc version. You can find an example using the newer API in the [citeproc readme](https://github.com/inukshuk/citeproc-ruby).

**Comment by rseac** [comment]
Thanks!
