### ISSUE TITLE
racc dependency needed

### ISSUE THREAD

**Issue by etc** [inukshuk/bibtex-ruby#163]
Upgrading to Ruby 3.3.0 produces an error:

```
/Users/bw68/.rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `require': cannot load such file -- racc/parser.rb (LoadError)
from /Users/bw68/.rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
from /Users/bw68/.rvm/gems/ruby-3.3.0/gems/bibtex-ruby-6.0.0/lib/bibtex/name_parser.rb:7:in `<top (required)>'
from /Users/bw68/.rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
```

For another user who had the same problem see [here](https://stackoverflow.com/questions/77729972/loaderror-for-racc-parser-rb-prevents-local-jekyll-website-build).

The problem seems to be that there is no `racc` dependency specified in the `bibtex-ruby` Gemfile (except in development mode). Manually adding `racc` to your own project Gemfile works, but I guess this should happen within `bibtex-ruby` itself?

**Comment by inukshuk** [comment]
Thanks! Looks like we'll have to make some more changes for 3.3 -- I'll try to push a release later.

**Comment by inukshuk** [comment]
OK 6.1.0 should work in Ruby 3.3.
