### ISSUE TITLE
Another MacRuby issue

### ISSUE THREAD

**Issue by stevenbedrick** [inukshuk/bibtex-ruby#2]
bibtex-ruby seems to have an issue with the latest nightlies of MacRuby. The following test program:

  require 'rubygems'
  require 'bibtex'
  bib = BibTeX.open('./test2.bib')
  puts bib.entries.size

Runs just fine under MRI, and ran just fine under earlier versions of post-0.8 MacRuby, but under the latest MacRuby nightlies, I get the following runtime error:

  bibtex-ruby-1.2.0/lib/bibtex/extensions.rb:28:in `block': uninitialized constant Array::StringReplacement (NameError)

The full stack trace is shown in this gist:

https://gist.github.com/844817

Note that a) test2.bib is a minimal file containing only one entry, and b) that bibtex-ruby seems to take an awfully long time to crash under MacRuby. 

Actually, in general, bibtex-ruby's performance under MacRuby is orders of magnitude worse than under MRI, but I don't know if that's anything you have control over- it's probably got more to do with RACC under MacRuby than anything else.

**Comment by mapreal19** [comment]
Closing since we don't support macruby anymore
